cc_binary (
    name = 'hello_libevhtp',
    srcs = [
        'HelloLibevhtp.cc',
    ],
    incs = [
        '../',
    ],
    deps = [
        '//thirdparty/libevent:libevent',
        '//thirdparty/libevhtp:libevhtp',
    ],

)

